# Give your application a name (useful for SonarQube and logging)
spring.application.name=devsecops-demo-app
 
# The port the app runs on INSIDE the container
# This matches the "8080" in your Jenkinsfile 'docker run -p 8081:8080' command
server.port=8080
 
# Logging levels (useful for debugging during the POC)
logging.level.org.springframework=INFO
logging.level.com.example.demo=DEBUG
